### PR TITLE
Add plugin namespaces RFC

### PR DESCRIPTION
**Pull request by jorisw**
See **[RFC](https://github.com/strapi/rfcs/blob/ee0387a89a9c72853d2c65c4af8f58ccef6e645d/rfcs/xxxx-plugin-namespaces.md)**.

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Hi @jorisw Can you change the link tu the preview of the rfc insteand :)

**Comment by jorisw** [comment]
Like this?

**Comment by alexandrebodin** [comment]
Thanks for this RFC.

Two points:

- Your RFC don't take into account name collision in the code if we strip the org name from the plugin (e.g strapi.plugins.xxxx) what xxx will it be ? If we have two plugins with the same name in two different orgs ?
- In v4 we will certainly move to a config to enable plugin and not use the npm package directly to offer more flexibility. (to be confirmed) In that case this would be solved pretty easily with some like what (eslint, gatsby ...) does with their plugin config

**Comment by jorisw** [comment]
> Your RFC don't take into account name collision in the code if we strip the org name from the plugin (e.g strapi.plugins.xxxx) what xxx will it be ? If we have two plugins with the same name in two different orgs ?

Actually my proposal deals with that in two ways:
- The short term proposal converts package with name `@my-org/strapi-plugin-lolcat-generator` to plugId `@my-org/lolcat-generator`
- The long term proposal converts package with name `@my-org/strapi-plugin-lolcat-generator` to `{ namespace: '@my-org', pluginId: 'lolcat-generator'}`.

> In v4 we will certainly move to a config to enable plugin and not use the npm package directly to offer more flexibility. (to be confirmed) In that case this would be solved pretty easily with some like what (eslint, gatsby ...) does with their plugin config

Sounds good. Plug-ins indeed should themselves provide their namespace and name on the long run. I've found reading `package.json` to be quite a hacky approach.

When is v4 due?

**Comment by derrickmehaffy** [comment]
> When is v4 due?

I don't believe we have a hard date for that yet.

**Comment by alexandrebodin** [comment]
Hi, going to close this RFC as we addressed this in v4

**Pull request closed without merging**
