### PR TITLE
Add admin panel customizations

### PR DESCRIPTION
**Pull request by torchsmith**
RFC: https://github.com/torchsmith/rfcs/blob/05d0e02920a070f5107e1999f3ea27ba8828bb37/rfcs/xxxx-template.md

Feature request to add injection zones to dashboard, and configuration options for Dashboard menu item and Dashboard.

### CODE REVIEW

**Comment by torchsmith** [comment]
Just signed the CLA now.

**Comment by torchsmith** [comment]
@alexandrebodin i added a description and updated title.

Not sure if you want me to try and fix the email thing or if you meant that you took care of it for me.

**Comment by torchsmith** [comment]
Looks like i got the check working :)

**Comment by torchsmith** [comment]
Just let me know if there is anything else you'd like me to adjust here :)

**Comment by torchsmith** [comment]
@iparidhi just tagging you into this.

**Comment by iparidhi** [comment]
Hi @torchsmith 

Thank you so much for your time and effort on this. Sorry that it took us some time to get back to you! 

* We’re aligned to add extension points and to make the UI customizable for sure
* This qualifies as a Feature request 
* You can start doing some new PRs, please also know that we are working on some features already to bring more customizable capabilities within the admin panel (like logo customization, primary color etc.) - there could be plausible conflicts. 

I’m closing this RFC, we encourage you to start doing some PRs on it given the above context. :)

**Pull request closed without merging**
