### PR TITLE
Add Categories to the Dynamic Zone components selector

### PR DESCRIPTION
**Pull request by misterdju**
[RFC preview link](https://github.com/misterdju/rfcs/blob/master/rfcs/xxxx-dz-category.md)

### CODE REVIEW

**Comment by soupette** [comment]
I love the idea especially when working with a lot of components from different categories.

**Comment by derrickmehaffy** [comment]
A bit of feedback also, I'm not sure if horizontal scrolling is the best idea, I like the layout that @misterdju showed off of just expanding vertically. (Thank you for the RFC)

**Comment by maevalienard** [comment]
I like your idea! I would suggest a collapse menu for the categories (i.e. default and media in your example). In my opinion, it would be more scalable with a lot of components divided into these different categories, what do you think?

**Comment by misterdju** [comment]
@maevalienard yes i think it is a good idea. 
Here is a mockup using the same UX than repeatable component.
collapse

**Comment by maevalienard** [comment]
Looks super cool to me! Can you confirm both categories and components would be sorted by alphabetical order (in order to follow the Content-types builder behavior)?

Many thanks for your time! 😄

**Comment by misterdju** [comment]
@maevalienard, yes i confirm both categories and components would be sorted by alphabetical order.

**Review by maevalienard — COMMENTED** [review]
LGTM :)

**Comment by maevalienard** [comment]
Sounds like every reviewer said to go ahead @misterdju, as discussed you can now properly start working on your proposition :)

**Comment by misterdju** [comment]
I have a question regarding the case where only one category is available. 
Do I display only the components or do I still display the category selector?
In the last case, do I open it by default?

**Comment by maevalienard** [comment]
According to the component behavior we're using, we can still display the category selector when there's only one category. If possible, I think it would be a nice idea to have it open by default :)

**Comment by alexandrebodin** [comment]
Hi @misterdju I'm going to merge this RFC so we can pass its status as `Active`

**Pull request merged**
