### PR TITLE
Global naming convention and getters

### PR DESCRIPTION
**Pull request by alexandrebodin**
**Introduce a global naming convetion for services, controllers and models.**

Read the proposal [here](https://github.com/strapi/rfcs/blob/proposal/global-naming-convention/rfcs/0000-template.md)

### CODE REVIEW

**Comment by Aurelsicoko** [comment]
LGTM 👍 

------

FYI, I tried to rewrite the entire controller User.js of the Users & Permissions plugin, and I found it was difficult to create the string to get a service. It wasn't natural to write :

```js
strapi.service('plugins::users-permissions.user').add(ctx.request.body)
```

but it was easier in my mind to write this instead

```js
strapi.plugin('users-permissions').service('user').add(ctx.request.body);
```

I think the main reason is that every part is dissociated from each other. First, I'm going into my plugin, I select the service I want to use, and then the method to call. Whereas, in the current proposal, the schema of thinking is a bit different.

**Current proposal:**
Call the service > Find the location > Call the method

**My draft proposal:**
Find the location > Call the service > Call the method

**Comment by alexandrebodin** [comment]
> LGTM 👍
>
> FYI, I tried to rewrite the entire controller User.js of the Users & Permissions plugin, and I found it was difficult to create the string to get a service. It wasn't natural to write :
>
> ```js
> strapi.service('plugins::users-permissions.user').add(ctx.request.body);
> ```
>
> but it was easier in my mind to write this instead
>
> ```js
> strapi
>   .plugin('users-permissions')
>   .service('user')
>   .add(ctx.request.body);
> ```
>
> I think the main reason is that every part is dissociated from each other. First, I'm going into my plugin, I select the service I want to use, and then the method to call. Whereas, in the current proposal, the schema of thinking is a bit different.
>
> **Current proposal:**
> Call the service > Find the location > Call the method
>
> **My draft proposal:**
> Find the location > Call the service > Call the method

Interesting thought. In most frameworks there is only one root access to avoid increasing the API surface area. It might be more a matter of habits because you have to do `strapi.plugins[plugin]` right now :).

Anyway as long as we keep global UIDs we can provide plugin scoped **getters** quite easily. Something like that would do:

```js
const ctx = {
  plugin(plugin) {
    return {
      service(key) {
        return ctx.service(`plugins::${plugin}.${key}`);
      },
      controller(key) {
        return ctx.controller(`plugins::${plugin}.${key}`);
      },
      model(key) {
        return ctx.model(`plugins::${plugin}.${key}`);
      },
    };
  },

  // root api
  service(key) {
    // implementation details
  },
  controller(key) {
    // implementation details
  },
  model(key) {
    // implementation details
  },
};
```

**Comment by derrickmehaffy** [comment]
I see @Aurelsicoko's point of view with the old structure for plugins but realistically it's just a matter of mindset. Either way I like the proposal from @alexandrebodin and think it will work the way it was described but documentation will be important here.

**Comment by Aurelsicoko** [comment]
That's what I think too... just another way of thinking. I shared my point of view, it doesn't mean we should implement it, you have a better experience than me on this topic @alexandrebodin

**Pull request merged**
